//урок номер 4  базовые операторы,математика
let a = ""+1+0;
console.log(a);
let b=""-1+0;
console.log(b);
let c=true+false;
console.log(c);
let d= 6/"3";
console.log(d);
let e ="2"*"3";
console.log(e);
let f= 4+5+"px";
console.log(f);
let g="$"+4+5;
console.log(g);
let h="4"-2;
console.log(h);
let i="4px"-2;
console.log(i);
let j="-9"+5;
let k="-9"-5;
console.log(j);
console.log(k);
let l=null+1;
console.log(l);
let m=undefined +1;
console.log(m);
let n ='\t\n'-2;
console.log(n);

let o= "1";
let p= "2";
console.log(+o+ +p);